# Generated by Django 4.2 on 2023-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='styles',
            field=models.ManyToManyField(related_name='artists', to='artists.styles'),
        ),
    ]
