# Generated by Django 4.2 on 2023-06-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_pirce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='prices.category_pirce'),
            preserve_default=False,
        ),
    ]
